### ISSUE TITLE
Leetcode problems on Binary Search

### ISSUE THREAD

**Issue by Shimrangupta22** [ayushi-ras/Hacktoberfest2023#49]
Some interview problems on binary search of Leetcode

**Comment by Shimrangupta22** [comment]
I want to submit code from bruteforce to optimal on some frequent asked leetcode problems on binary search ...please allow me to this

**Comment by Shimrangupta22** [comment]
please assign me this issue @ayushi-ras

**Comment by dynamicdhxx** [comment]
Heyy!
I would like to provide binary search problems from leetcode. Kindly assign me the issue 😊.

**Comment by mmehraa** [comment]
Hi, I have created a pull request for binary search in java. I hope you like the solution.
